<?php
/**
 * EEL Accounts
 * Copyright (c) 2026 James Elstone
 * Licensed under the GNU Affero General Public License v3.0 (AGPLv3)
 * See LICENSE file for details.
 */
declare(strict_types=1);

final class Ct600BuilderService
{
    public function buildCt600Xml(int $companyId, int $taxYearId): array
    {
        $company = (new CompanyRepository())->fetchCompanyDetails($companyId);
        $taxYear = (new TaxYearRepository())->fetchTaxYear($companyId, $taxYearId);
        $settings = $companyId > 0 ? (new CompanySettingsStore($companyId))->all() : [];
        $errors = [];
        $warnings = ['TODO: Complete CT600 XML schema mapping before production submission.'];

        if (!is_array($company) || empty($company['is_active'])) {
            $errors[] = 'Company does not exist or is inactive.';
        }
        if ($taxYear === null) {
            $errors[] = 'Selected tax year does not belong to the company.';
        }
        if (trim((string)($company['company_number'] ?? '')) === '') {
            $errors[] = 'Company number is missing.';
        }
        if (trim((string)($settings['utr'] ?? '')) === '') {
            $errors[] = 'Corporation Tax UTR is missing from company settings.';
        }

        if ($taxYear !== null) {
            $days = (new DateTimeImmutable((string)$taxYear['period_start']))->diff(new DateTimeImmutable((string)$taxYear['period_end']))->days + 1;
            if ($days > 365) {
                $errors[] = 'The selected accounting period is longer than 12 months; CT accounting periods may need to be split.';
            }
        }

        if ($errors !== []) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => $errors];
        }

        $ct = (new CorporationTaxComputationService())->fetchSummary($companyId, $taxYearId);
        if (empty($ct['available'])) {
            $errors = array_merge($errors, (array)($ct['errors'] ?? ['Corporation Tax computation is not available.']));
        }
        if ($errors !== []) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => $errors];
        }

        $estimatedTax = (float)($ct['estimated_corporation_tax'] ?? 0);
        $losses = $this->lossApplication($companyId, $taxYearId, (float)($ct['taxable_profit'] ?? 0));
        $directory = APP_ROOT . 'outbound' . DIRECTORY_SEPARATOR . 'hmrc' . DIRECTORY_SEPARATOR . 'ct600';
        if (!is_dir($directory) && !mkdir($directory, 0775, true) && !is_dir($directory)) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => ['Could not create CT600 output directory.']];
        }

        $path = $directory . DIRECTORY_SEPARATOR . 'ct600_' . $companyId . '_' . $taxYearId . '.xml';
        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
            . '<!-- Internal draft CT600 package generated by eel. TODO: complete against HMRC Corporation Tax Online XML schema before production filing. -->' . "\n"
            . '<CT600Draft>' . "\n"
            . '  <CompanyName>' . $this->e((string)$company['company_name']) . '</CompanyName>' . "\n"
            . '  <CompanyNumber>' . $this->e((string)$company['company_number']) . '</CompanyNumber>' . "\n"
            . '  <UTR>' . $this->e((string)$settings['utr']) . '</UTR>' . "\n"
            . '  <PeriodStart>' . $this->e((string)$taxYear['period_start']) . '</PeriodStart>' . "\n"
            . '  <PeriodEnd>' . $this->e((string)$taxYear['period_end']) . '</PeriodEnd>' . "\n"
            . '  <EstimatedCorporationTax>' . number_format($estimatedTax, 2, '.', '') . '</EstimatedCorporationTax>' . "\n"
            . '  <LossesBroughtForward>' . number_format((float)$losses['brought_forward'], 2, '.', '') . '</LossesBroughtForward>' . "\n"
            . '  <LossesUsed>' . number_format((float)$losses['used'], 2, '.', '') . '</LossesUsed>' . "\n"
            . '  <LossesCarriedForward>' . number_format((float)$losses['remaining'], 2, '.', '') . '</LossesCarriedForward>' . "\n"
            . '</CT600Draft>' . "\n";

        if (file_put_contents($path, $xml) === false) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => ['Could not write CT600 XML file.']];
        }

        return ['ok' => true, 'path' => $path, 'warnings' => $warnings, 'errors' => [], 'losses' => $losses];
    }

    private function lossApplication(int $companyId, int $taxYearId, float $taxableProfit): array
    {
        if (!InterfaceDB::tableExists('tax_loss_pools')) {
            return ['brought_forward' => 0.0, 'used' => 0.0, 'remaining' => 0.0];
        }

        $available = (float)InterfaceDB::fetchColumn(
            'SELECT COALESCE(SUM(remaining_amount), 0)
             FROM tax_loss_pools
             WHERE company_id = :company_id
               AND origin_tax_year_id <> :tax_year_id',
            ['company_id' => $companyId, 'tax_year_id' => $taxYearId]
        );
        $used = $taxableProfit > 0 ? min($taxableProfit, $available) : 0.0;

        return [
            'brought_forward' => round($available, 2),
            'used' => round($used, 2),
            'remaining' => round($available - $used, 2),
        ];
    }

    private function e(string $value): string
    {
        return htmlspecialchars($value, ENT_XML1 | ENT_QUOTES, 'UTF-8');
    }
}
