ALTER TABLE journals
  MODIFY source_type enum('bank_csv','director_loan_register','expense_register','manual','asset_register','asset_depreciation','asset_disposal') NOT NULL;

CREATE TABLE IF NOT EXISTS asset_register (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  company_id int(11) NOT NULL,
  asset_code varchar(64) NOT NULL,
  description varchar(255) NOT NULL,
  category varchar(64) NOT NULL,
  nominal_account_id int(11) NOT NULL,
  accum_dep_nominal_id int(11) NOT NULL,
  purchase_date date NOT NULL,
  cost decimal(12,2) NOT NULL,
  useful_life_years int(11) NOT NULL DEFAULT 3,
  depreciation_method varchar(32) NOT NULL DEFAULT 'straight_line',
  residual_value decimal(12,2) NOT NULL DEFAULT 0.00,
  status varchar(32) NOT NULL DEFAULT 'active',
  linked_journal_id bigint(20) DEFAULT NULL,
  linked_transaction_id bigint(20) DEFAULT NULL,
  disposal_date date DEFAULT NULL,
  disposal_proceeds decimal(12,2) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_asset_register_company_code (company_id, asset_code),
  KEY idx_asset_register_company_status (company_id, status, purchase_date),
  KEY idx_asset_register_nominal (nominal_account_id),
  KEY idx_asset_register_accum_dep_nominal (accum_dep_nominal_id),
  KEY idx_asset_register_linked_journal (linked_journal_id),
  KEY idx_asset_register_linked_transaction (linked_transaction_id),
  CONSTRAINT fk_asset_register_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_asset_register_nominal FOREIGN KEY (nominal_account_id) REFERENCES nominal_accounts (id) ON UPDATE CASCADE,
  CONSTRAINT fk_asset_register_accum_dep_nominal FOREIGN KEY (accum_dep_nominal_id) REFERENCES nominal_accounts (id) ON UPDATE CASCADE,
  CONSTRAINT fk_asset_register_linked_journal FOREIGN KEY (linked_journal_id) REFERENCES journals (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT fk_asset_register_linked_transaction FOREIGN KEY (linked_transaction_id) REFERENCES transactions (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_asset_register_cost CHECK (cost > 0),
  CONSTRAINT chk_asset_register_useful_life CHECK (useful_life_years > 0),
  CONSTRAINT chk_asset_register_residual CHECK (residual_value >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS asset_depreciation_entries (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  asset_id bigint(20) NOT NULL,
  tax_year_id int(11) NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  amount decimal(12,2) NOT NULL,
  journal_id bigint(20) DEFAULT NULL,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_asset_depreciation_period (asset_id, tax_year_id, period_start, period_end),
  KEY idx_asset_depreciation_tax_year (tax_year_id),
  KEY idx_asset_depreciation_journal (journal_id),
  CONSTRAINT fk_asset_depreciation_asset FOREIGN KEY (asset_id) REFERENCES asset_register (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_asset_depreciation_tax_year FOREIGN KEY (tax_year_id) REFERENCES tax_years (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_asset_depreciation_journal FOREIGN KEY (journal_id) REFERENCES journals (id) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT chk_asset_depreciation_period CHECK (period_start <= period_end),
  CONSTRAINT chk_asset_depreciation_amount CHECK (amount > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
