-- FRS 105 micro-entity thresholds are sourced by the Rates / Thresholds refresh
-- from GOV.UK. Do not seed values here: fresh installations require a successful
-- source refresh before the thresholds become available.
