CREATE TABLE IF NOT EXISTS corporation_tax_treatment_rules (
  id int(11) NOT NULL AUTO_INCREMENT,
  rule_code varchar(64) NOT NULL,
  rule_version varchar(32) NOT NULL,
  priority int(11) NOT NULL DEFAULT 100,
  nominal_account_id int(11) DEFAULT NULL,
  nominal_code varchar(32) DEFAULT NULL,
  account_type enum('income','cost_of_sales','expense','asset','liability','equity') DEFAULT NULL,
  name_contains varchar(255) DEFAULT NULL,
  tax_treatment enum('allowable','disallowable','capital','other') NOT NULL,
  effective_from date DEFAULT NULL,
  effective_to date DEFAULT NULL,
  source_url varchar(500) NOT NULL,
  source_checked_at date NOT NULL,
  rationale text NOT NULL,
  review_status enum('seeded','needs_review','reviewed') NOT NULL DEFAULT 'seeded',
  is_active tinyint(1) NOT NULL DEFAULT 1,
  created_at datetime NOT NULL DEFAULT current_timestamp(),
  updated_at datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (id),
  UNIQUE KEY uq_ct_treatment_rule_version (rule_code, rule_version),
  KEY idx_ct_treatment_rules_lookup (is_active, priority, effective_from, effective_to),
  KEY idx_ct_treatment_rules_nominal (nominal_account_id),
  KEY idx_ct_treatment_rules_code (nominal_code),
  CONSTRAINT fk_ct_treatment_rule_nominal FOREIGN KEY (nominal_account_id) REFERENCES nominal_accounts (id) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO corporation_tax_treatment_rules (
  rule_code,
  rule_version,
  priority,
  nominal_account_id,
  nominal_code,
  tax_treatment,
  source_url,
  source_checked_at,
  rationale,
  review_status,
  is_active
)
SELECT
  'client_entertainment_disallowable',
  'hmrc-bim45000-2026-05-26',
  10,
  na.id,
  na.code,
  'disallowable',
  'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim45000',
  '2026-05-26',
  'Business entertainment and gifts are normally not allowable deductions for Corporation Tax. This rule overrides the nominal default for client entertainment.',
  'seeded',
  1
FROM nominal_accounts na
WHERE na.code = '6130'
ON DUPLICATE KEY UPDATE
  priority = VALUES(priority),
  nominal_account_id = VALUES(nominal_account_id),
  nominal_code = VALUES(nominal_code),
  tax_treatment = VALUES(tax_treatment),
  source_url = VALUES(source_url),
  source_checked_at = VALUES(source_checked_at),
  rationale = VALUES(rationale),
  review_status = VALUES(review_status),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO corporation_tax_treatment_rules (
  rule_code,
  rule_version,
  priority,
  nominal_code,
  account_type,
  name_contains,
  tax_treatment,
  source_url,
  source_checked_at,
  rationale,
  review_status,
  is_active
) VALUES
  (
    'fixed_asset_tools_equipment_capital',
    'govuk-ca-2026-05-26',
    30,
    '1300',
    NULL,
    NULL,
    'capital',
    'https://www.gov.uk/capital-allowances/what-you-can-claim-on',
    '2026-05-26',
    'Fixed asset purchases are capital items. Corporation Tax relief is normally considered through capital allowances rather than ordinary revenue deduction.',
    'seeded',
    1
  ),
  (
    'fixed_asset_plant_machinery_capital',
    'govuk-ca-2026-05-26',
    31,
    '1310',
    NULL,
    NULL,
    'capital',
    'https://www.gov.uk/capital-allowances/what-you-can-claim-on',
    '2026-05-26',
    'Fixed asset purchases are capital items. Corporation Tax relief is normally considered through capital allowances rather than ordinary revenue deduction.',
    'seeded',
    1
  ),
  (
    'fixed_asset_motor_vehicles_capital',
    'govuk-ca-2026-05-26',
    32,
    '1320',
    NULL,
    NULL,
    'capital',
    'https://www.gov.uk/capital-allowances/what-you-can-claim-on',
    '2026-05-26',
    'Fixed asset purchases are capital items. Corporation Tax relief is normally considered through capital allowances rather than ordinary revenue deduction.',
    'seeded',
    1
  ),
  (
    'fines_penalties_disallowable',
    'hmrc-bim38515-2026-05-26',
    40,
    NULL,
    'expense',
    'penalt',
    'disallowable',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim38515',
    '2026-05-26',
    'Penalties for breaching the law are not allowable. This catches expense nominals whose names include penalty/penalties.',
    'seeded',
    1
  ),
  (
    'fines_disallowable',
    'hmrc-bim38515-2026-05-26',
    41,
    NULL,
    'expense',
    'fine',
    'disallowable',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim38515',
    '2026-05-26',
    'Fines for infractions of the law are not allowable. This catches expense nominals whose names include fine/fines.',
    'seeded',
    1
  ),
  (
    'companies_house_penalties_disallowable',
    'hmrc-bim38515-2026-05-26',
    42,
    NULL,
    'expense',
    'Companies House Penalt',
    'disallowable',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim38515',
    '2026-05-26',
    'Companies House penalties are treated as penalties rather than ordinary business expenses.',
    'seeded',
    1
  ),
  (
    'hmrc_penalties_disallowable',
    'hmrc-bim38515-2026-05-26',
    43,
    NULL,
    'expense',
    'HMRC Penalt',
    'disallowable',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim38515',
    '2026-05-26',
    'HMRC penalties are treated as penalties rather than ordinary business expenses.',
    'seeded',
    1
  ),
  (
    'private_costs_disallowable',
    'hmrc-bim37600-2026-05-26',
    50,
    NULL,
    'expense',
    'Private',
    'disallowable',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim37600',
    '2026-05-26',
    'A non-trade or private purpose can preclude deduction where the business element cannot be objectively separated.',
    'needs_review',
    1
  ),
  (
    'personal_costs_disallowable',
    'hmrc-bim37600-2026-05-26',
    51,
    NULL,
    'expense',
    'Personal',
    'disallowable',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim37600',
    '2026-05-26',
    'Personal costs normally need disallowance or apportionment review under the wholly and exclusively principle.',
    'needs_review',
    1
  ),
  (
    'donations_need_review',
    'hmrc-bim45072-2026-05-26',
    60,
    NULL,
    'expense',
    'Donation',
    'other',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim45072',
    '2026-05-26',
    'Charitable gifts and donations have specific conditions and company relief mechanics. Review rather than treating as ordinary allowable expense.',
    'needs_review',
    1
  ),
  (
    'charity_gifts_need_review',
    'hmrc-bim45072-2026-05-26',
    61,
    NULL,
    'expense',
    'Charit',
    'other',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim45072',
    '2026-05-26',
    'Charity gifts and donations need review for wholly and exclusively conditions and company qualifying charitable donations treatment.',
    'needs_review',
    1
  ),
  (
    'legal_fees_need_review',
    'hmrc-bim35500-2026-05-26',
    70,
    NULL,
    'expense',
    'Legal',
    'other',
    'https://www.gov.uk/hmrc-internal-manuals/business-income-manual/bim35500',
    '2026-05-26',
    'Legal and professional costs may be revenue or capital depending on the underlying matter. Review before relying on CT treatment.',
    'needs_review',
    1
  ),
  (
    'interest_loan_relationships_need_review',
    'hmrc-cfm30130-2026-05-26',
    80,
    NULL,
    'expense',
    'Interest',
    'other',
    'https://www.gov.uk/hmrc-internal-manuals/corporate-finance-manual/cfm30130',
    '2026-05-26',
    'Company interest and finance debits fall under the loan relationships code and may need further restrictions or purpose review.',
    'needs_review',
    1
  ),
  (
    'ordinary_cost_of_sales_allowable',
    'govuk-expenses-2026-05-26',
    1000,
    NULL,
    'cost_of_sales',
    NULL,
    'allowable',
    'https://www.gov.uk/guidance/company-expenses-you-can-deduct-before-paying-corporation-tax',
    '2026-05-26',
    'Ordinary revenue costs are deductible where they are not capital, not specifically disallowed, and incurred wholly for business purposes.',
    'seeded',
    1
  ),
  (
    'ordinary_expenses_allowable',
    'govuk-expenses-2026-05-26',
    1010,
    NULL,
    'expense',
    NULL,
    'allowable',
    'https://www.gov.uk/guidance/company-expenses-you-can-deduct-before-paying-corporation-tax',
    '2026-05-26',
    'Ordinary revenue expenses are deductible where they are not capital, not specifically disallowed, and incurred wholly for business purposes.',
    'seeded',
    1
  )
ON DUPLICATE KEY UPDATE
  priority = VALUES(priority),
  nominal_code = VALUES(nominal_code),
  account_type = VALUES(account_type),
  name_contains = VALUES(name_contains),
  tax_treatment = VALUES(tax_treatment),
  source_url = VALUES(source_url),
  source_checked_at = VALUES(source_checked_at),
  rationale = VALUES(rationale),
  review_status = VALUES(review_status),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;

INSERT INTO corporation_tax_treatment_rules (
  rule_code,
  rule_version,
  priority,
  nominal_account_id,
  nominal_code,
  tax_treatment,
  source_url,
  source_checked_at,
  rationale,
  review_status,
  is_active
)
SELECT
  'depreciation_addback_disallowable',
  'hmrc-ca11110-2026-05-26',
  20,
  na.id,
  na.code,
  'disallowable',
  'https://www.gov.uk/hmrc-internal-manuals/capital-allowances-manual/ca11110',
  '2026-05-26',
  'Depreciation is added back when adjusting accounting profit to taxable profit. Capital allowances are deducted separately.',
  'seeded',
  1
FROM nominal_accounts na
WHERE na.code = '6200'
ON DUPLICATE KEY UPDATE
  priority = VALUES(priority),
  nominal_account_id = VALUES(nominal_account_id),
  nominal_code = VALUES(nominal_code),
  tax_treatment = VALUES(tax_treatment),
  source_url = VALUES(source_url),
  source_checked_at = VALUES(source_checked_at),
  rationale = VALUES(rationale),
  review_status = VALUES(review_status),
  is_active = VALUES(is_active),
  updated_at = CURRENT_TIMESTAMP;
