INSERT INTO ixbrl_fact_mappings (
  fact_key, taxonomy_concept, namespace_uri, local_name, label, value_type,
  calculation_type, source_key, sign_multiplier, period_type, unit_ref,
  decimals_value, context_profile, dimensions_json, comparative_enabled,
  is_required, sort_order, is_active
) VALUES
(
  'gross_profit_loss',
  'core:GrossProfitLoss',
  'http://xbrl.frc.org.uk/fr/2026-01-01/core',
  'GrossProfitLoss',
  'Gross profit / loss',
  'numeric',
  'derived',
  'gross_profit_loss',
  1,
  'duration',
  'GBP',
  '2',
  'duration',
  NULL,
  1,
  1,
  125,
  1
),
(
  'operating_profit_loss',
  'core:OperatingProfitLoss',
  'http://xbrl.frc.org.uk/fr/2026-01-01/core',
  'OperatingProfitLoss',
  'Operating profit / loss',
  'numeric',
  'derived',
  'profit_loss_before_tax',
  1,
  'duration',
  'GBP',
  '2',
  'duration',
  NULL,
  1,
  1,
  147,
  1
)
ON DUPLICATE KEY UPDATE
  taxonomy_concept = VALUES(taxonomy_concept),
  namespace_uri = VALUES(namespace_uri),
  local_name = VALUES(local_name),
  label = VALUES(label),
  value_type = VALUES(value_type),
  calculation_type = VALUES(calculation_type),
  source_key = VALUES(source_key),
  sign_multiplier = VALUES(sign_multiplier),
  period_type = VALUES(period_type),
  unit_ref = VALUES(unit_ref),
  decimals_value = VALUES(decimals_value),
  context_profile = VALUES(context_profile),
  dimensions_json = VALUES(dimensions_json),
  comparative_enabled = VALUES(comparative_enabled),
  is_required = VALUES(is_required),
  sort_order = VALUES(sort_order),
  is_active = VALUES(is_active);
