ALTER TABLE ixbrl_generation_runs
  ADD COLUMN IF NOT EXISTS basis_version varchar(50) DEFAULT NULL AFTER taxonomy_profile,
  ADD COLUMN IF NOT EXISTS basis_hash char(64) DEFAULT NULL AFTER basis_version,
  ADD COLUMN IF NOT EXISTS external_validated_sha256 char(64) DEFAULT NULL AFTER external_validated_at;

ALTER TABLE ixbrl_generation_facts
  ADD COLUMN IF NOT EXISTS dimensions_json longtext DEFAULT NULL AFTER context_ref;

ALTER TABLE ixbrl_fact_mappings
  MODIFY COLUMN calculation_type enum(
    'nominal_subtype_sum','nominal_account_sum','manual','derived',
    'company_field','period_field','disclosure_field','disclosure_statement','absence_statement','application_value','fixed_marker'
  ) NOT NULL,
  ADD COLUMN IF NOT EXISTS namespace_uri varchar(255) DEFAULT NULL AFTER taxonomy_concept,
  ADD COLUMN IF NOT EXISTS local_name varchar(255) DEFAULT NULL AFTER namespace_uri,
  ADD COLUMN IF NOT EXISTS period_type enum('instant','duration') DEFAULT NULL AFTER sign_multiplier,
  ADD COLUMN IF NOT EXISTS unit_ref varchar(50) DEFAULT NULL AFTER period_type,
  ADD COLUMN IF NOT EXISTS decimals_value varchar(20) DEFAULT NULL AFTER unit_ref,
  ADD COLUMN IF NOT EXISTS context_profile varchar(100) DEFAULT NULL AFTER decimals_value,
  ADD COLUMN IF NOT EXISTS dimensions_json longtext DEFAULT NULL AFTER context_profile,
  ADD COLUMN IF NOT EXISTS comparative_enabled tinyint(1) NOT NULL DEFAULT 0 AFTER dimensions_json;

DELETE FROM ixbrl_fact_mappings;

INSERT INTO ixbrl_fact_mappings (
  fact_key, taxonomy_concept, namespace_uri, local_name, label, value_type,
  calculation_type, source_key, sign_multiplier, period_type, unit_ref,
  decimals_value, context_profile, dimensions_json, comparative_enabled,
  is_required, sort_order, is_active
) VALUES
('entity_name','bus:EntityCurrentLegalOrRegisteredName','http://xbrl.frc.org.uk/cd/2026-01-01/business','EntityCurrentLegalOrRegisteredName','Entity name','text','company_field','company_name',1,'duration',NULL,NULL,'duration',NULL,0,1,10,1),
('company_number','bus:UKCompaniesHouseRegisteredNumber','http://xbrl.frc.org.uk/cd/2026-01-01/business','UKCompaniesHouseRegisteredNumber','Company number','text','company_field','company_number',1,'duration',NULL,NULL,'duration',NULL,0,1,20,1),
('country_formation_or_incorporation','bus:CountryFormationOrIncorporation','http://xbrl.frc.org.uk/cd/2026-01-01/business','CountryFormationOrIncorporation','Country of formation or incorporation','text','fixed_marker','companies_house_jurisdiction',1,'duration',NULL,NULL,'duration_country_formation','{"countries:CountriesRegionsDimension":"countries:EnglandWales"}',0,1,21,1),
('legal_form_entity','bus:LegalFormEntity','http://xbrl.frc.org.uk/cd/2026-01-01/business','LegalFormEntity','Legal form of entity','text','fixed_marker','companies_house_type',1,'duration',NULL,NULL,'duration_legal_form','{"bus:LegalFormEntityDimension":"bus:PrivateLimitedCompanyLtd"}',0,1,22,1),
('registered_office_address_line_1','bus:AddressLine1','http://xbrl.frc.org.uk/cd/2026-01-01/business','AddressLine1','Registered office address line 1','text','company_field','registered_office_address_line_1',1,'duration',NULL,NULL,'duration_registered_office','{"bus:EntityContactTypeDimension":"bus:RegisteredOffice","countries:CountriesRegionsDimension":"countries:UnitedKingdom"}',0,1,23,1),
('registered_office_address_line_2','bus:AddressLine2','http://xbrl.frc.org.uk/cd/2026-01-01/business','AddressLine2','Registered office address line 2','text','company_field','registered_office_address_line_2',1,'duration',NULL,NULL,'duration_registered_office','{"bus:EntityContactTypeDimension":"bus:RegisteredOffice","countries:CountriesRegionsDimension":"countries:UnitedKingdom"}',0,1,24,1),
('registered_office_address_line_3','bus:AddressLine3','http://xbrl.frc.org.uk/cd/2026-01-01/business','AddressLine3','Registered office address line 3','text','company_field','registered_office_address_line_3',1,'duration',NULL,NULL,'duration_registered_office','{"bus:EntityContactTypeDimension":"bus:RegisteredOffice","countries:CountriesRegionsDimension":"countries:UnitedKingdom"}',0,1,25,1),
('registered_office_postal_code','bus:PostalCodeZip','http://xbrl.frc.org.uk/cd/2026-01-01/business','PostalCodeZip','Registered office postal code','text','company_field','registered_office_postal_code',1,'duration',NULL,NULL,'duration_registered_office','{"bus:EntityContactTypeDimension":"bus:RegisteredOffice","countries:CountriesRegionsDimension":"countries:UnitedKingdom"}',0,1,26,1),
('period_start','bus:StartDateForPeriodCoveredByReport','http://xbrl.frc.org.uk/cd/2026-01-01/business','StartDateForPeriodCoveredByReport','Period start','date','period_field','period_start',1,'instant',NULL,NULL,'instant_start',NULL,0,1,30,1),
('period_end','bus:EndDateForPeriodCoveredByReport','http://xbrl.frc.org.uk/cd/2026-01-01/business','EndDateForPeriodCoveredByReport','Period end','date','period_field','period_end',1,'instant',NULL,NULL,'instant_end',NULL,0,1,40,1),
('balance_sheet_date','bus:BalanceSheetDate','http://xbrl.frc.org.uk/cd/2026-01-01/business','BalanceSheetDate','Balance sheet date','date','period_field','period_end',1,'instant',NULL,NULL,'instant_end',NULL,0,1,50,1),
('accounts_approval_date','core:DateAuthorisationFinancialStatementsForIssue','http://xbrl.frc.org.uk/fr/2026-01-01/core','DateAuthorisationFinancialStatementsForIssue','Accounts approval date','date','disclosure_field','accounts_approval_date',1,'instant',NULL,NULL,'instant_approval',NULL,0,1,60,1),
('approving_director_name','bus:NameEntityOfficer','http://xbrl.frc.org.uk/cd/2026-01-01/business','NameEntityOfficer','Director approving the financial statements','text','disclosure_field','approving_director_name',1,'duration',NULL,NULL,'duration_director_1','{"bus:EntityOfficersDimension":"bus:Director1"}',0,1,70,1),
('director_signing_financial_statements','core:DirectorSigningFinancialStatements','http://xbrl.frc.org.uk/fr/2026-01-01/core','DirectorSigningFinancialStatements','Director signing financial statements','text','fixed_marker','approving_director_name',1,'duration',NULL,NULL,'duration_director_1','{"bus:EntityOfficersDimension":"bus:Director1"}',0,1,75,1),
('entity_trading_status','bus:EntityTradingStatus','http://xbrl.frc.org.uk/cd/2026-01-01/business','EntityTradingStatus','Entity trading status','text','fixed_marker','entity_trading_status',1,'duration',NULL,NULL,'duration_trading_status',NULL,0,1,80,1),
('accounting_standards_applied','bus:AccountingStandardsApplied','http://xbrl.frc.org.uk/cd/2026-01-01/business','AccountingStandardsApplied','Accounting standards applied','text','fixed_marker','accounting_standard',1,'duration',NULL,NULL,'duration_accounting_standards','{"bus:AccountingStandardsDimension":"bus:Micro-entities"}',0,1,85,1),
('accounts_status','bus:AccountsStatusAuditedOrUnaudited','http://xbrl.frc.org.uk/cd/2026-01-01/business','AccountsStatusAuditedOrUnaudited','Accounts status audited or unaudited','text','fixed_marker','audit_exempt_section_477',1,'duration',NULL,NULL,'duration_accounts_status','{"bus:AccountsStatusDimension":"bus:AuditExempt-NoAccountantsReport"}',0,1,90,1),
('turnover','core:TurnoverRevenue','http://xbrl.frc.org.uk/fr/2026-01-01/core','TurnoverRevenue','Turnover','numeric','derived','turnover',1,'duration','GBP','2','duration',NULL,1,1,100,1),
('other_income','core:OtherOperatingIncomeFormat2','http://xbrl.frc.org.uk/fr/2026-01-01/core','OtherOperatingIncomeFormat2','Other income','numeric','derived','other_income',1,'duration','GBP','2','duration',NULL,1,1,110,1),
('raw_materials_consumables','core:RawMaterialsConsumablesUsed','http://xbrl.frc.org.uk/fr/2026-01-01/core','RawMaterialsConsumablesUsed','Raw materials and consumables','numeric','derived','raw_materials_consumables',1,'duration','GBP','2','duration',NULL,1,1,120,1),
('staff_costs','core:StaffCostsEmployeeBenefitsExpense','http://xbrl.frc.org.uk/fr/2026-01-01/core','StaffCostsEmployeeBenefitsExpense','Staff costs','numeric','derived','staff_costs',1,'duration','GBP','2','duration',NULL,1,1,130,1),
('depreciation_write_offs','core:DepreciationAmortisationImpairmentExpense','http://xbrl.frc.org.uk/fr/2026-01-01/core','DepreciationAmortisationImpairmentExpense','Depreciation and other amounts written off assets','numeric','derived','depreciation_write_offs',1,'duration','GBP','2','duration',NULL,1,1,140,1),
('other_charges','core:OtherExternalCharges','http://xbrl.frc.org.uk/fr/2026-01-01/core','OtherExternalCharges','Other charges','numeric','derived','other_charges',1,'duration','GBP','2','duration',NULL,1,1,145,1),
('tax_on_profit','core:TaxTaxCreditOnProfitOrLossOnOrdinaryActivities','http://xbrl.frc.org.uk/fr/2026-01-01/core','TaxTaxCreditOnProfitOrLossOnOrdinaryActivities','Tax on profit / loss','numeric','derived','tax_on_profit',1,'duration','GBP','2','duration',NULL,1,1,150,1),
('profit_loss','core:ProfitLoss','http://xbrl.frc.org.uk/fr/2026-01-01/core','ProfitLoss','Profit / loss for the financial year','numeric','derived','profit_loss',1,'duration','GBP','2','duration',NULL,1,1,160,1),
('fixed_assets','core:FixedAssets','http://xbrl.frc.org.uk/fr/2026-01-01/core','FixedAssets','Fixed assets','numeric','derived','fixed_assets',1,'instant','GBP','2','instant_end',NULL,1,1,200,1),
('current_assets','core:CurrentAssets','http://xbrl.frc.org.uk/fr/2026-01-01/core','CurrentAssets','Current assets','numeric','derived','current_assets',1,'instant','GBP','2','instant_end',NULL,1,1,210,1),
('prepayments_accrued_income','core:PrepaymentsAccruedIncome','http://xbrl.frc.org.uk/fr/2026-01-01/core','PrepaymentsAccruedIncome','Prepayments and accrued income','numeric','derived','prepayments_accrued_income',1,'instant','GBP','2','instant_end',NULL,1,1,215,1),
('creditors_within_one_year','core:Creditors','http://xbrl.frc.org.uk/fr/2026-01-01/core','Creditors','Creditors within one year','numeric','derived','creditors_within_one_year',1,'instant','GBP','2','instant_end_creditors_within','{"core:MaturitiesOrExpirationPeriodsDimension":"core:WithinOneYear"}',1,1,220,1),
('net_current_assets_liabilities','core:NetCurrentAssetsLiabilities','http://xbrl.frc.org.uk/fr/2026-01-01/core','NetCurrentAssetsLiabilities','Net current assets / liabilities','numeric','derived','net_current_assets_liabilities',1,'instant','GBP','2','instant_end',NULL,1,1,230,1),
('total_assets_less_current_liabilities','core:TotalAssetsLessCurrentLiabilities','http://xbrl.frc.org.uk/fr/2026-01-01/core','TotalAssetsLessCurrentLiabilities','Total assets less current liabilities','numeric','derived','total_assets_less_current_liabilities',1,'instant','GBP','2','instant_end',NULL,1,1,240,1),
('creditors_after_one_year','core:Creditors','http://xbrl.frc.org.uk/fr/2026-01-01/core','Creditors','Creditors after more than one year','numeric','derived','creditors_after_more_than_one_year',1,'instant','GBP','2','instant_end_creditors_after','{"core:MaturitiesOrExpirationPeriodsDimension":"core:AfterOneYear"}',1,1,250,1),
('net_assets_liabilities','core:NetAssetsLiabilities','http://xbrl.frc.org.uk/fr/2026-01-01/core','NetAssetsLiabilities','Net assets / liabilities','numeric','derived','net_assets_liabilities',1,'instant','GBP','2','instant_end',NULL,1,1,260,1),
('equity','core:Equity','http://xbrl.frc.org.uk/fr/2026-01-01/core','Equity','Equity','numeric','derived','equity_capital_reserves',1,'instant','GBP','2','instant_end',NULL,1,1,270,1),
('average_number_employees','core:AverageNumberEmployeesDuringPeriod','http://xbrl.frc.org.uk/fr/2026-01-01/core','AverageNumberEmployeesDuringPeriod','Average number of employees','numeric','disclosure_field','average_number_employees',1,'duration','pure','0','duration',NULL,1,1,300,1),
('entity_dormant','bus:EntityDormantTruefalse','http://xbrl.frc.org.uk/cd/2026-01-01/business','EntityDormantTruefalse','Entity dormant','boolean','disclosure_field','entity_dormant',1,'duration',NULL,NULL,'duration',NULL,0,1,310,1),
('small_companies_regime_statement','direp:StatementThatAccountsHaveBeenPreparedInAccordanceWithProvisionsSmallCompaniesRegime','http://xbrl.frc.org.uk/reports/2026-01-01/direp','StatementThatAccountsHaveBeenPreparedInAccordanceWithProvisionsSmallCompaniesRegime','Small companies regime statement','text','disclosure_statement','prepared_under_small_companies_regime',1,'duration',NULL,NULL,'duration',NULL,0,1,320,1),
('audit_exemption_statement','direp:StatementThatCompanyEntitledToExemptionFromAuditUnderSection477CompaniesAct2006RelatingToSmallCompanies','http://xbrl.frc.org.uk/reports/2026-01-01/direp','StatementThatCompanyEntitledToExemptionFromAuditUnderSection477CompaniesAct2006RelatingToSmallCompanies','Audit exemption statement','text','disclosure_statement','audit_exempt_section_477',1,'duration',NULL,NULL,'duration',NULL,0,1,330,1),
('directors_responsibility_statement','direp:StatementThatDirectorsAcknowledgeTheirResponsibilitiesUnderCompaniesAct','http://xbrl.frc.org.uk/reports/2026-01-01/direp','StatementThatDirectorsAcknowledgeTheirResponsibilitiesUnderCompaniesAct','Directors responsibilities statement','text','disclosure_statement','directors_acknowledge_responsibilities',1,'duration',NULL,NULL,'duration',NULL,0,1,340,1),
('members_no_audit_statement','direp:StatementThatMembersHaveNotRequiredCompanyToObtainAnAudit','http://xbrl.frc.org.uk/reports/2026-01-01/direp','StatementThatMembersHaveNotRequiredCompanyToObtainAnAudit','Members have not required an audit statement','text','disclosure_statement','members_have_not_required_audit',1,'duration',NULL,NULL,'duration',NULL,0,1,350,1),
('no_material_off_balance_sheet_arrangements','core:GeneralDescriptionAnyOff-balanceSheetArrangementsIncludingNaturePurposeFinancialImpactOnEntity','http://xbrl.frc.org.uk/fr/2026-01-01/core','GeneralDescriptionAnyOff-balanceSheetArrangementsIncludingNaturePurposeFinancialImpactOnEntity','No material off-balance sheet arrangements','text','absence_statement','has_material_off_balance_sheet_arrangements',1,'duration',NULL,NULL,'duration',NULL,0,1,360,1),
('no_director_advances_or_credits','direp:GeneralDescriptionAdvancesCreditsToDirectorsIncludingTermsInterestRates','http://xbrl.frc.org.uk/reports/2026-01-01/direp','GeneralDescriptionAdvancesCreditsToDirectorsIncludingTermsInterestRates','Director advances and credits to directors','text','director_loan_statement','has_director_advances_credits_or_guarantees',1,'duration',NULL,NULL,'duration',NULL,0,1,361,1),
('no_director_guarantees','direp:GeneralDescriptionGuaranteesTheirTermsDirectors','http://xbrl.frc.org.uk/reports/2026-01-01/direp','GeneralDescriptionGuaranteesTheirTermsDirectors','No guarantees on behalf of directors','text','absence_statement','has_director_advances_credits_or_guarantees',1,'duration',NULL,NULL,'duration',NULL,0,1,362,1),
('no_capital_commitments','core:DescriptionCapitalCommitments','http://xbrl.frc.org.uk/fr/2026-01-01/core','DescriptionCapitalCommitments','No capital commitments','text','absence_statement','has_financial_commitments_guarantees_or_contingencies',1,'duration',NULL,NULL,'duration',NULL,0,1,363,1),
('no_financial_commitments','core:DescriptionFinancialCommitmentsOtherThanCapitalCommitments','http://xbrl.frc.org.uk/fr/2026-01-01/core','DescriptionFinancialCommitmentsOtherThanCapitalCommitments','No other financial commitments','text','absence_statement','has_financial_commitments_guarantees_or_contingencies',1,'duration',NULL,NULL,'duration',NULL,0,1,364,1),
('no_contingent_liabilities','core:GeneralDescriptionContingentLiabilitiesIncludingFinancialEffectUncertaintiesPossibleReimbursement','http://xbrl.frc.org.uk/fr/2026-01-01/core','GeneralDescriptionContingentLiabilitiesIncludingFinancialEffectUncertaintiesPossibleReimbursement','No contingent liabilities','text','absence_statement','has_financial_commitments_guarantees_or_contingencies',1,'duration',NULL,NULL,'duration',NULL,0,1,365,1),
('production_software','bus:NameProductionSoftware','http://xbrl.frc.org.uk/cd/2026-01-01/business','NameProductionSoftware','Production software','text','application_value','app_name',1,'duration',NULL,NULL,'duration',NULL,0,1,370,1),
('production_software_version','bus:VersionProductionSoftware','http://xbrl.frc.org.uk/cd/2026-01-01/business','VersionProductionSoftware','Production software version','text','application_value','app_version',1,'duration',NULL,NULL,'duration',NULL,0,1,371,1);
