-- Full CT600A evidence, section 464A review, and unsupported supplementary-page scope.

CREATE TABLE IF NOT EXISTS corporation_tax_scope_confirmations (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id INT NOT NULL,
  accounting_period_id INT NOT NULL,
  scope_version VARCHAR(50) NOT NULL,
  answers_json LONGTEXT NOT NULL,
  revision INT NOT NULL DEFAULT 1,
  confirmed_by VARCHAR(100) DEFAULT NULL,
  confirmed_at DATETIME DEFAULT NULL,
  basis_hash CHAR(64) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_ct_scope_period (company_id, accounting_period_id),
  CONSTRAINT fk_ct_scope_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ct_scope_period FOREIGN KEY (accounting_period_id) REFERENCES accounting_periods (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS corporation_tax_ct600a_events (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id INT NOT NULL,
  accounting_period_id INT NOT NULL,
  ct_period_id INT NOT NULL,
  originating_ct_period_id INT DEFAULT NULL,
  party_id BIGINT NOT NULL,
  event_kind ENUM('opening_outstanding','release','write_off','later_repayment','s464a_benefit','s464a_return_payment') NOT NULL,
  event_date DATE NOT NULL,
  origin_date DATE DEFAULT NULL,
  amount DECIMAL(14,2) NOT NULL,
  source_type ENUM('bank_transaction','journal','prior_return','manual_evidence') NOT NULL,
  source_id BIGINT DEFAULT NULL,
  evidence_reference VARCHAR(255) NOT NULL,
  explanation TEXT NOT NULL,
  matching_status ENUM('clear','potential_464c','confirmed_464c') NOT NULL DEFAULT 'clear',
  approval_role ENUM('director','adviser') NOT NULL,
  approved_by VARCHAR(100) NOT NULL,
  approved_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_ct600a_event_period (company_id, accounting_period_id, ct_period_id, event_date),
  KEY idx_ct600a_event_origin (originating_ct_period_id),
  KEY idx_ct600a_event_party (party_id, event_date),
  CONSTRAINT fk_ct600a_event_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ct600a_event_period FOREIGN KEY (accounting_period_id) REFERENCES accounting_periods (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ct600a_event_ct_period FOREIGN KEY (ct_period_id) REFERENCES corporation_tax_periods (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ct600a_event_origin FOREIGN KEY (originating_ct_period_id) REFERENCES corporation_tax_periods (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT fk_ct600a_event_party FOREIGN KEY (party_id) REFERENCES company_parties (id) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT chk_ct600a_event_amount CHECK (amount > 0),
  CONSTRAINT chk_ct600a_event_dates CHECK (origin_date IS NULL OR origin_date <= event_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS corporation_tax_ct600a_reviews (
  id BIGINT NOT NULL AUTO_INCREMENT,
  company_id INT NOT NULL,
  accounting_period_id INT NOT NULL,
  ct_period_id INT NOT NULL,
  review_version VARCHAR(50) NOT NULL,
  answers_json LONGTEXT NOT NULL,
  approver_role ENUM('director','adviser') NOT NULL,
  approved_by VARCHAR(100) NOT NULL,
  confirmation_note TEXT DEFAULT NULL,
  evidence_manifest_json LONGTEXT NOT NULL,
  basis_hash CHAR(64) NOT NULL,
  confirmed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_ct600a_review_period (ct_period_id),
  KEY idx_ct600a_review_company_period (company_id, accounting_period_id),
  CONSTRAINT fk_ct600a_review_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ct600a_review_period FOREIGN KEY (accounting_period_id) REFERENCES accounting_periods (id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_ct600a_review_ct_period FOREIGN KEY (ct_period_id) REFERENCES corporation_tax_periods (id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
