<?php
/**
 * EEL Accounts
 * Copyright (c) 2026 James Elstone
 * Licensed under the GNU Affero General Public License v3.0 (AGPLv3)
 * See LICENSE file for details.
 */
declare(strict_types=1);


namespace eel_accounts\Service;

final class Ct600BuilderService
{
    public function buildCt600Xml(int $companyId, int $accountingPeriodId): array
    {
        $periodService = new \eel_accounts\Service\CorporationTaxPeriodService();
        $sync = $periodService->syncForAccountingPeriod($companyId, $accountingPeriodId);
        $ctPeriodId = (int)($sync['periods'][0]['id'] ?? 0);
        if ($ctPeriodId <= 0) {
            return ['ok' => false, 'path' => null, 'warnings' => ['TODO: Complete CT600 XML schema mapping before production submission.'], 'errors' => ['No CT period could be derived for this accounting period.']];
        }

        return $this->buildCt600XmlForCtPeriod($companyId, $ctPeriodId);
    }

    public function buildCt600XmlForCtPeriod(int $companyId, int $ctPeriodId): array
    {
        $company = (new \eel_accounts\Repository\CompanyRepository())->fetchCompanyDetails($companyId);
        $ctPeriod = (new \eel_accounts\Service\CorporationTaxPeriodService())->fetch($companyId, $ctPeriodId);
        $accountingPeriodId = (int)($ctPeriod['accounting_period_id'] ?? 0);
        $accountingPeriod = $accountingPeriodId > 0
            ? (new \eel_accounts\Repository\AccountingPeriodRepository())->fetchAccountingPeriod($companyId, $accountingPeriodId)
            : null;
        $settings = $companyId > 0 ? (new \eel_accounts\Store\CompanySettingsStore($companyId))->all() : [];
        $errors = [];
        $warnings = ['TODO: Complete CT600 XML schema mapping before production submission.'];

        if (!is_array($company) || empty($company['is_active'])) {
            $errors[] = 'Company does not exist or is inactive.';
        }
        if ($accountingPeriod === null) {
            $errors[] = 'Selected accounting period does not belong to the company.';
        }
        if ($ctPeriod === null) {
            $errors[] = 'Selected CT period does not belong to the company.';
        }
        if (trim((string)($company['company_number'] ?? '')) === '') {
            $errors[] = 'Company number is missing.';
        }
        if (trim((string)($settings['utr'] ?? '')) === '') {
            $errors[] = 'Corporation Tax UTR is missing from company settings.';
        }

        if ($ctPeriod !== null) {
            $days = (new \DateTimeImmutable((string)$ctPeriod['period_start']))->diff(new \DateTimeImmutable((string)$ctPeriod['period_end']))->days + 1;
            if ($days > 365) {
                $errors[] = 'The selected CT period is longer than 12 months.';
            }
        }

        if ($errors !== []) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => $errors];
        }

        $ct = (new \eel_accounts\Service\CorporationTaxComputationService())->fetchSummaryForCtPeriodId($companyId, $ctPeriodId);
        if (empty($ct['available'])) {
            $errors = array_merge($errors, (array)($ct['errors'] ?? ['Corporation Tax computation is not available.']));
        }
        if ($errors !== []) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => $errors];
        }

        $estimatedTax = (float)($ct['estimated_corporation_tax'] ?? 0);
        $losses = [
            'brought_forward' => round((float)($ct['losses_brought_forward'] ?? 0), 2),
            'used' => round((float)($ct['losses_used'] ?? 0), 2),
            'remaining' => round((float)($ct['losses_carried_forward'] ?? 0), 2),
        ];
        $directory = APP_ROOT . 'outbound' . DIRECTORY_SEPARATOR . 'hmrc' . DIRECTORY_SEPARATOR . 'ct600';
        if (!is_dir($directory) && !mkdir($directory, 0775, true) && !is_dir($directory)) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => ['Could not create CT600 output directory.']];
        }

        $path = $directory . DIRECTORY_SEPARATOR . 'ct600_' . $companyId . '_' . $accountingPeriodId . '_' . (int)($ctPeriod['sequence_no'] ?? 0) . '.xml';
        $xml = '<?xml version="1.0" encoding="UTF-8"?>' . "\n"
            . '<!-- Internal draft CT600 package generated by eel. TODO: complete against HMRC Corporation Tax Online XML schema before production filing. -->' . "\n"
            . '<CT600Draft>' . "\n"
            . '  <CompanyName>' . $this->e((string)$company['company_name']) . '</CompanyName>' . "\n"
            . '  <CompanyNumber>' . $this->e((string)$company['company_number']) . '</CompanyNumber>' . "\n"
            . '  <UTR>' . $this->e((string)$settings['utr']) . '</UTR>' . "\n"
            . '  <AccountingPeriodStart>' . $this->e((string)$accountingPeriod['period_start']) . '</AccountingPeriodStart>' . "\n"
            . '  <AccountingPeriodEnd>' . $this->e((string)$accountingPeriod['period_end']) . '</AccountingPeriodEnd>' . "\n"
            . '  <CtPeriodSequence>' . (int)($ctPeriod['sequence_no'] ?? 0) . '</CtPeriodSequence>' . "\n"
            . '  <PeriodStart>' . $this->e((string)$ctPeriod['period_start']) . '</PeriodStart>' . "\n"
            . '  <PeriodEnd>' . $this->e((string)$ctPeriod['period_end']) . '</PeriodEnd>' . "\n"
            . '  <EstimatedCorporationTax>' . number_format($estimatedTax, 2, '.', '') . '</EstimatedCorporationTax>' . "\n"
            . '  <LossesBroughtForward>' . number_format((float)$losses['brought_forward'], 2, '.', '') . '</LossesBroughtForward>' . "\n"
            . '  <LossesUsed>' . number_format((float)$losses['used'], 2, '.', '') . '</LossesUsed>' . "\n"
            . '  <LossesCarriedForward>' . number_format((float)$losses['remaining'], 2, '.', '') . '</LossesCarriedForward>' . "\n"
            . '</CT600Draft>' . "\n";

        if (file_put_contents($path, $xml) === false) {
            return ['ok' => false, 'path' => null, 'warnings' => $warnings, 'errors' => ['Could not write CT600 XML file.']];
        }

        return ['ok' => true, 'path' => $path, 'warnings' => $warnings, 'errors' => [], 'losses' => $losses];
    }

    private function e(string $value): string
    {
        return htmlspecialchars($value, \ENT_XML1 | \ENT_QUOTES, 'UTF-8');
    }
}
